version: '3'

services:
  web:
    build: .
    user: ${UID:-1000}:${GID:-1000}
    command: sh deploy/start_django.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  npm_dev:
    build: .
    user: ${UID:-1000}:${GID:-1000}
    command: sh deploy/start_npm.sh
    volumes:
      - .:/code
    ports:
      - "8080:8080"
