version: '3'

services:
  web:
    build: .
    user: ${UID:-1000}:${GID:-1000}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  npm_dev:
    build: .
    user: ${UID:-1000}:${GID:-1000}
    command: npm --prefix vue_frontend/ run start
    volumes:
      - .:/code
    ports:
      - "8080:8080"
